Add Ensure-Feature, Ensure-Installed, and Ensure-Source.
Inedo/inedox-chocolatey pull request #7
Opened 2018-09-07 21:45 UTC by BenLubar

2018-09-17 12:55 UTC, gdivis approved these changes

2018-09-19 22:03 UTC, jrasch requested changes
I believe we need to keep the `ScriptNamespace` attributes, or at least add it to the AssemblyInfo file indicating that it's required since we have multiple `Ensure-Package` and `Collect-Packages` operations.

2018-09-21 06:34 UTC, BenLubar commented
@thoven it is added to AssemblyInfo: https://github.com/Inedo/inedox-chocolatey/pull/7/files#diff-21517e2bfe8b6b5841eb3fa6a2216f40

2018-09-21 14:07 UTC, jrasch approved these changes

2018-09-21 14:08 UTC, jrasch commented
No idea how I missed that...

2018-09-21 14:08 UTC, merged